/**
 * The comparison QUERY two databases get compared by.
 *
 * Replaces `buildDiffSql` in `shared/components/schema-diff-dialog/schema-diff-dialog.component.ts`.
 * The naming stays honest, per the audit and the brief: nothing here diffs anything. It writes SQL into a
 * new query tab, the user runs it, and the server does the comparing. That is a genuinely useful thing —
 * the result is inspectable, editable and exportable, which a built-in diff view would not be — but it is
 * not a diff, and the dialog says so.
 *
 * ── Why this is engine-aware, and what the Angular version did instead ──────────────────────
 *
 * The generated SQL was **T-SQL only**: three-part `[db].INFORMATION_SCHEMA.TABLES` names,
 * `[bracketed]` identifiers, `ISNULL`, `FULL OUTER JOIN`, `OBJECT_SCHEMA_NAME(…, DB_ID('…'))` and
 * `sys.indexes`. The dialog offered it for whatever the focused connection was, so on PostgreSQL or MySQL
 * it produced a tab full of SQL that cannot parse — after a dialog with four checkboxes and a database
 * picker, which is a long way to walk to a syntax error.
 *
 * The three engines are not symmetrical here and the asymmetry is the interesting part:
 *
 * - **SQL Server** can name another database in a query (`[other].INFORMATION_SCHEMA.…`), so a real
 *   two-database comparison is one statement. The T-SQL below is the Angular one, kept.
 * - **MySQL** calls a database a schema, and `information_schema` spans all of them, so the same
 *   comparison is `WHERE TABLE_SCHEMA IN (source, target)` — different SQL, same answer.
 * - **PostgreSQL** cannot query across databases at all without `dblink` or `postgres_fdw`. There is no
 *   statement to generate, so `buildDiffQuery` REFUSES with that sentence instead of emitting T-SQL and
 *   letting the server say something less useful. Comparing two SCHEMAS inside one database is the
 *   PostgreSQL-shaped version of this feature and is not what the dialog asks for; it is J-69.
 */

import type { DatabaseEngine } from '@joinery/shared';

/** Which object families to compare. All four default on, as the Angular dialog had them. */
export interface DiffSections {
  readonly tables: boolean;
  readonly views: boolean;
  readonly routines: boolean;
  readonly indexes: boolean;
}

export const ALL_SECTIONS: DiffSections = {
  tables: true,
  views: true,
  routines: true,
  indexes: true,
};

/** The sections, in the order the query emits them, with the label the dialog shows. */
export const SECTION_LABELS: readonly {
  readonly key: keyof DiffSections;
  readonly label: string;
}[] = [
  { key: 'tables', label: 'Tables and columns' },
  { key: 'views', label: 'Views' },
  { key: 'routines', label: 'Stored procedures and functions' },
  { key: 'indexes', label: 'Indexes' },
];

export interface DiffQueryInput {
  readonly engine: DatabaseEngine;
  readonly source: string;
  readonly target: string;
  readonly sections: DiffSections;
}

export type DiffQuery =
  { readonly ok: true; readonly sql: string } | { readonly ok: false; readonly reason: string };

/**
 * Whether this engine can be asked to compare two databases in one statement at all.
 *
 * Exported so the dialog can say why BEFORE the user fills it in, rather than refusing at the end. The
 * refusal still exists in `buildDiffQuery` — the palette can reach the command with any engine focused,
 * and a check the caller may skip is not a check.
 */
export function canCompareDatabases(engine: DatabaseEngine): boolean {
  return engine !== 'postgresql';
}

/** The sentence a refused engine gets. One copy, so the dialog and the generator cannot disagree. */
export const POSTGRES_REFUSAL =
  'PostgreSQL cannot query across databases, so there is no single statement that compares two of ' +
  'them. Connect to each database and compare the results, or install dblink / postgres_fdw.';

export function buildDiffQuery(input: DiffQueryInput): DiffQuery {
  const { engine, source, target, sections } = input;

  if (source.trim() === '' || target.trim() === '') {
    return { ok: false, reason: 'Pick a source and a target database.' };
  }
  if (source === target) {
    return {
      ok: false,
      reason: 'Pick two different databases — a database always matches itself.',
    };
  }
  if (!canCompareDatabases(engine)) return { ok: false, reason: POSTGRES_REFUSAL };
  if (!SECTION_LABELS.some(section => sections[section.key])) {
    return { ok: false, reason: 'Choose at least one thing to compare.' };
  }

  const parts: string[] = [
    `-- Schema comparison: ${source} vs ${target}`,
    // No timestamp. The Angular header carried `new Date().toLocaleString()`, which made the generated
    // SQL differ on every press — so a saved comparison query showed as modified the moment it was
    // regenerated, and two runs could not be diffed against each other.
    '-- Generated by Joinery. Run it: each section reports what one side has and the other does not.',
    '',
  ];

  const builder = engine === 'mssql' ? MSSQL_SECTIONS : MYSQL_SECTIONS;
  for (const section of SECTION_LABELS) {
    if (!sections[section.key]) continue;
    parts.push(banner(section.label), builder[section.key]({ source, target }), '');
  }

  return { ok: true, sql: parts.join('\n').trimEnd() + '\n' };
}

function banner(label: string): string {
  const rule = '-- '.padEnd(3) + '='.repeat(60);
  return `${rule}\n-- ${label.toUpperCase()}\n${rule}`;
}

interface Pair {
  readonly source: string;
  readonly target: string;
}

type SectionBuilder = Record<keyof DiffSections, (pair: Pair) => string>;

// ── SQL Server ────────────────────────────────────────────────────────────────────────────────
//
// Ported from the Angular original with three changes, each a correction rather than a restyle:
//
// 1. **identifiers are escaped**. The original interpolated the picked names straight into
//    `[${db}]` and into string literals (`'${this.sourceDb} only' AS [Location]`), so a database
//    called `a]b` produced unparseable SQL and one called `a'b` produced SQL that parsed as
//    something else. The names come from a picker, so this is a correctness bug rather than an
//    injection route — but `bracket()` and `quote()` cost nothing and remove the question.
// 2. **routines covers functions too**, not just `ROUTINE_TYPE = 'PROCEDURE'`. A function that
//    exists on one side and not the other is exactly the difference the section is for, and the
//    original silently ignored it while the checkbox said "Stored Procedures".
// 3. **the index comparison joins on table as well as name**. The original's `NOT EXISTS` matched
//    on `t.name = s.name` alone, so an index called `IX_created_at` on `orders` was reported as
//    present because a DIFFERENT table had one with the same name. Index names are not unique per
//    database in SQL Server, so that was wrong for the most common naming convention there is.

const MSSQL_SECTIONS: SectionBuilder = {
  tables: ({ source, target }) => `
-- Tables one side has and the other does not
SELECT ${quote(`${source} only`)} AS [Location], s.TABLE_SCHEMA, s.TABLE_NAME
FROM ${bracket(source)}.INFORMATION_SCHEMA.TABLES s
WHERE s.TABLE_TYPE = 'BASE TABLE'
  AND NOT EXISTS (
    SELECT 1 FROM ${bracket(target)}.INFORMATION_SCHEMA.TABLES t
    WHERE t.TABLE_SCHEMA = s.TABLE_SCHEMA AND t.TABLE_NAME = s.TABLE_NAME AND t.TABLE_TYPE = 'BASE TABLE'
  )
UNION ALL
SELECT ${quote(`${target} only`)}, t.TABLE_SCHEMA, t.TABLE_NAME
FROM ${bracket(target)}.INFORMATION_SCHEMA.TABLES t
WHERE t.TABLE_TYPE = 'BASE TABLE'
  AND NOT EXISTS (
    SELECT 1 FROM ${bracket(source)}.INFORMATION_SCHEMA.TABLES s
    WHERE s.TABLE_SCHEMA = t.TABLE_SCHEMA AND s.TABLE_NAME = t.TABLE_NAME AND s.TABLE_TYPE = 'BASE TABLE'
  )
ORDER BY TABLE_SCHEMA, TABLE_NAME;

-- Column differences inside the tables both sides have
SELECT
  COALESCE(s.TABLE_SCHEMA, t.TABLE_SCHEMA) AS [Schema],
  COALESCE(s.TABLE_NAME, t.TABLE_NAME) AS [Table],
  COALESCE(s.COLUMN_NAME, t.COLUMN_NAME) AS [Column],
  CASE
    WHEN s.COLUMN_NAME IS NULL THEN ${quote(`${target} only`)}
    WHEN t.COLUMN_NAME IS NULL THEN ${quote(`${source} only`)}
    ELSE 'Type mismatch'
  END AS [Difference],
  s.DATA_TYPE AS [SourceType],
  s.CHARACTER_MAXIMUM_LENGTH AS [SourceMaxLen],
  t.DATA_TYPE AS [TargetType],
  t.CHARACTER_MAXIMUM_LENGTH AS [TargetMaxLen]
FROM ${bracket(source)}.INFORMATION_SCHEMA.COLUMNS s
FULL OUTER JOIN ${bracket(target)}.INFORMATION_SCHEMA.COLUMNS t
  ON s.TABLE_SCHEMA = t.TABLE_SCHEMA
  AND s.TABLE_NAME = t.TABLE_NAME
  AND s.COLUMN_NAME = t.COLUMN_NAME
WHERE (s.COLUMN_NAME IS NULL OR t.COLUMN_NAME IS NULL
  OR s.DATA_TYPE <> t.DATA_TYPE
  OR ISNULL(s.CHARACTER_MAXIMUM_LENGTH, 0) <> ISNULL(t.CHARACTER_MAXIMUM_LENGTH, 0))
  AND EXISTS (
    SELECT 1 FROM ${bracket(source)}.INFORMATION_SCHEMA.TABLES st
    WHERE st.TABLE_SCHEMA = COALESCE(s.TABLE_SCHEMA, t.TABLE_SCHEMA)
      AND st.TABLE_NAME = COALESCE(s.TABLE_NAME, t.TABLE_NAME)
  )
  AND EXISTS (
    SELECT 1 FROM ${bracket(target)}.INFORMATION_SCHEMA.TABLES tt
    WHERE tt.TABLE_SCHEMA = COALESCE(s.TABLE_SCHEMA, t.TABLE_SCHEMA)
      AND tt.TABLE_NAME = COALESCE(s.TABLE_NAME, t.TABLE_NAME)
  )
ORDER BY [Schema], [Table], [Column];`,

  views: ({ source, target }) => `
SELECT ${quote(`${source} only`)} AS [Location], s.TABLE_SCHEMA, s.TABLE_NAME AS [ViewName]
FROM ${bracket(source)}.INFORMATION_SCHEMA.VIEWS s
WHERE NOT EXISTS (
  SELECT 1 FROM ${bracket(target)}.INFORMATION_SCHEMA.VIEWS t
  WHERE t.TABLE_SCHEMA = s.TABLE_SCHEMA AND t.TABLE_NAME = s.TABLE_NAME
)
UNION ALL
SELECT ${quote(`${target} only`)}, t.TABLE_SCHEMA, t.TABLE_NAME
FROM ${bracket(target)}.INFORMATION_SCHEMA.VIEWS t
WHERE NOT EXISTS (
  SELECT 1 FROM ${bracket(source)}.INFORMATION_SCHEMA.VIEWS s
  WHERE s.TABLE_SCHEMA = t.TABLE_SCHEMA AND s.TABLE_NAME = t.TABLE_NAME
)
ORDER BY TABLE_SCHEMA, [ViewName];`,

  routines: ({ source, target }) => `
SELECT ${quote(`${source} only`)} AS [Location], s.ROUTINE_SCHEMA, s.ROUTINE_NAME, s.ROUTINE_TYPE
FROM ${bracket(source)}.INFORMATION_SCHEMA.ROUTINES s
WHERE NOT EXISTS (
  SELECT 1 FROM ${bracket(target)}.INFORMATION_SCHEMA.ROUTINES t
  WHERE t.ROUTINE_SCHEMA = s.ROUTINE_SCHEMA AND t.ROUTINE_NAME = s.ROUTINE_NAME
    AND t.ROUTINE_TYPE = s.ROUTINE_TYPE
)
UNION ALL
SELECT ${quote(`${target} only`)}, t.ROUTINE_SCHEMA, t.ROUTINE_NAME, t.ROUTINE_TYPE
FROM ${bracket(target)}.INFORMATION_SCHEMA.ROUTINES t
WHERE NOT EXISTS (
  SELECT 1 FROM ${bracket(source)}.INFORMATION_SCHEMA.ROUTINES s
  WHERE s.ROUTINE_SCHEMA = t.ROUTINE_SCHEMA AND s.ROUTINE_NAME = t.ROUTINE_NAME
    AND s.ROUTINE_TYPE = t.ROUTINE_TYPE
)
ORDER BY ROUTINE_SCHEMA, ROUTINE_NAME;`,

  indexes: ({ source, target }) => `
SELECT ${quote(`${source} only`)} AS [Location],
  OBJECT_SCHEMA_NAME(si.object_id, DB_ID(${quote(source)})) AS [Schema],
  OBJECT_NAME(si.object_id, DB_ID(${quote(source)})) AS [Table],
  si.name AS [IndexName], si.type_desc
FROM ${bracket(source)}.sys.indexes si
INNER JOIN ${bracket(source)}.sys.tables st ON si.object_id = st.object_id
WHERE si.name IS NOT NULL
  AND NOT EXISTS (
    SELECT 1 FROM ${bracket(target)}.sys.indexes ti
    INNER JOIN ${bracket(target)}.sys.tables tt ON ti.object_id = tt.object_id
    WHERE ti.name = si.name AND tt.name = st.name AND SCHEMA_NAME(tt.schema_id) = SCHEMA_NAME(st.schema_id)
  )
UNION ALL
SELECT ${quote(`${target} only`)},
  OBJECT_SCHEMA_NAME(ti.object_id, DB_ID(${quote(target)})),
  OBJECT_NAME(ti.object_id, DB_ID(${quote(target)})),
  ti.name, ti.type_desc
FROM ${bracket(target)}.sys.indexes ti
INNER JOIN ${bracket(target)}.sys.tables tt ON ti.object_id = tt.object_id
WHERE ti.name IS NOT NULL
  AND NOT EXISTS (
    SELECT 1 FROM ${bracket(source)}.sys.indexes si
    INNER JOIN ${bracket(source)}.sys.tables st ON si.object_id = st.object_id
    WHERE si.name = ti.name AND st.name = tt.name AND SCHEMA_NAME(st.schema_id) = SCHEMA_NAME(tt.schema_id)
  )
ORDER BY [Schema], [Table], [IndexName];`,
};

// ── MySQL ─────────────────────────────────────────────────────────────────────────────────────
//
// New. `information_schema` spans every database on the server, so the comparison is a self-join over
// two `TABLE_SCHEMA` values rather than two three-part names — and `STATISTICS` replaces `sys.indexes`.

const MYSQL_SECTIONS: SectionBuilder = {
  tables: ({ source, target }) => `
-- Tables one side has and the other does not
SELECT CONCAT(s.TABLE_SCHEMA, ' only') AS Location, s.TABLE_NAME
FROM information_schema.TABLES s
WHERE s.TABLE_SCHEMA IN (${quote(source)}, ${quote(target)}) AND s.TABLE_TYPE = 'BASE TABLE'
  AND NOT EXISTS (
    SELECT 1 FROM information_schema.TABLES t
    WHERE t.TABLE_SCHEMA = IF(s.TABLE_SCHEMA = ${quote(source)}, ${quote(target)}, ${quote(source)})
      AND t.TABLE_NAME = s.TABLE_NAME AND t.TABLE_TYPE = 'BASE TABLE'
  )
ORDER BY Location, s.TABLE_NAME;

-- Column differences inside the tables both sides have
SELECT
  s.TABLE_NAME AS \`Table\`,
  s.COLUMN_NAME AS \`Column\`,
  'Type mismatch' AS Difference,
  s.COLUMN_TYPE AS SourceType,
  t.COLUMN_TYPE AS TargetType
FROM information_schema.COLUMNS s
JOIN information_schema.COLUMNS t
  ON t.TABLE_SCHEMA = ${quote(target)} AND t.TABLE_NAME = s.TABLE_NAME AND t.COLUMN_NAME = s.COLUMN_NAME
WHERE s.TABLE_SCHEMA = ${quote(source)} AND s.COLUMN_TYPE <> t.COLUMN_TYPE
UNION ALL
SELECT s.TABLE_NAME, s.COLUMN_NAME, CONCAT(${quote(source)}, ' only'), s.COLUMN_TYPE, NULL
FROM information_schema.COLUMNS s
WHERE s.TABLE_SCHEMA = ${quote(source)}
  AND EXISTS (SELECT 1 FROM information_schema.TABLES t
              WHERE t.TABLE_SCHEMA = ${quote(target)} AND t.TABLE_NAME = s.TABLE_NAME)
  AND NOT EXISTS (SELECT 1 FROM information_schema.COLUMNS t
                  WHERE t.TABLE_SCHEMA = ${quote(target)} AND t.TABLE_NAME = s.TABLE_NAME
                    AND t.COLUMN_NAME = s.COLUMN_NAME)
UNION ALL
SELECT t.TABLE_NAME, t.COLUMN_NAME, CONCAT(${quote(target)}, ' only'), NULL, t.COLUMN_TYPE
FROM information_schema.COLUMNS t
WHERE t.TABLE_SCHEMA = ${quote(target)}
  AND EXISTS (SELECT 1 FROM information_schema.TABLES s
              WHERE s.TABLE_SCHEMA = ${quote(source)} AND s.TABLE_NAME = t.TABLE_NAME)
  AND NOT EXISTS (SELECT 1 FROM information_schema.COLUMNS s
                  WHERE s.TABLE_SCHEMA = ${quote(source)} AND s.TABLE_NAME = t.TABLE_NAME
                    AND s.COLUMN_NAME = t.COLUMN_NAME)
ORDER BY \`Table\`, \`Column\`;`,

  views: ({ source, target }) => `
SELECT CONCAT(s.TABLE_SCHEMA, ' only') AS Location, s.TABLE_NAME AS ViewName
FROM information_schema.VIEWS s
WHERE s.TABLE_SCHEMA IN (${quote(source)}, ${quote(target)})
  AND NOT EXISTS (
    SELECT 1 FROM information_schema.VIEWS t
    WHERE t.TABLE_SCHEMA = IF(s.TABLE_SCHEMA = ${quote(source)}, ${quote(target)}, ${quote(source)})
      AND t.TABLE_NAME = s.TABLE_NAME
  )
ORDER BY Location, ViewName;`,

  routines: ({ source, target }) => `
SELECT CONCAT(s.ROUTINE_SCHEMA, ' only') AS Location, s.ROUTINE_NAME, s.ROUTINE_TYPE
FROM information_schema.ROUTINES s
WHERE s.ROUTINE_SCHEMA IN (${quote(source)}, ${quote(target)})
  AND NOT EXISTS (
    SELECT 1 FROM information_schema.ROUTINES t
    WHERE t.ROUTINE_SCHEMA = IF(s.ROUTINE_SCHEMA = ${quote(source)}, ${quote(target)}, ${quote(source)})
      AND t.ROUTINE_NAME = s.ROUTINE_NAME AND t.ROUTINE_TYPE = s.ROUTINE_TYPE
  )
ORDER BY Location, s.ROUTINE_NAME;`,

  indexes: ({ source, target }) => `
SELECT CONCAT(s.TABLE_SCHEMA, ' only') AS Location, s.TABLE_NAME AS \`Table\`, s.INDEX_NAME AS IndexName
FROM information_schema.STATISTICS s
WHERE s.TABLE_SCHEMA IN (${quote(source)}, ${quote(target)}) AND s.SEQ_IN_INDEX = 1
  AND NOT EXISTS (
    SELECT 1 FROM information_schema.STATISTICS t
    WHERE t.TABLE_SCHEMA = IF(s.TABLE_SCHEMA = ${quote(source)}, ${quote(target)}, ${quote(source)})
      AND t.TABLE_NAME = s.TABLE_NAME AND t.INDEX_NAME = s.INDEX_NAME
  )
ORDER BY Location, \`Table\`, IndexName;`,
};

/** `[name]`, with `]` doubled — the same escape `main/src/utils/tsql-builder.ts` uses. */
function bracket(name: string): string {
  return `[${name.replace(/]/g, ']]')}]`;
}

/** A single-quoted literal, with `'` doubled. Portable across all three engines. */
function quote(value: string): string {
  return `'${value.replace(/'/g, "''")}'`;
}
